### ISSUE TITLE
17 MB of library?

### ISSUE THREAD

**Issue by borjaruiz** [JoanZapata/android-pdfview#86]
Hi, I've integrated the library with my app, and it has increased 17 MB. Is there a jar or am I doing something wrong?

I've downloaded the library from here to use it in Eclipse: https://drive.google.com/file/d/0BwRMp8dK9LMLQmVhZkNMQ19WMUU/view
(The library folder size is 17 MB)

I've added it in project properties-Android-Add...

Thanks in advance.

**Comment by dector** [comment]
Try to use files from [versioneye](https://www.versioneye.com/java/com.joanzapata.pdfview:android-pdfview/1.0.2).

Version [1.0.2 file](http://search.maven.org/remotecontent?filepath=com/joanzapata/pdfview/android-pdfview/1.0.2/android-pdfview-1.0.2.jar)

**Comment by omidaminiva** [comment]
when I use the jar file I get this error:
02-25 23:37:20.160: E/AndroidRuntime(29728): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load vudroid from loader dalvik.system.PathClassLoader[dexPath=/data/app/com.vayyoo.activity-182.apk,libraryPath=/data/app-lib/com.vayyoo.activity-182]: findLibrary returned null

PS: I am using it in eclipse and I only added android-pdfview-1.0.2.jar to my libs

**Comment by JoanZapata** [comment]
You can find official releases on [maven central](http://search.maven.org/#browse%7C-1653732968). What you need is the `.aar` or `.apklib` file depending on your build system.
The library is 5 MB large.

**Comment by amrboxit4me** [comment]
use in manifest it will reduce download size..check Analyzes Apk from Build menu in Android studio after activating it
```
 <application
        android:extractNativeLibs="false">

```
