### ISSUE TITLE
Can not show pdf file created by image

### ISSUE THREAD

**Issue by vuvanly** [JoanZapata/android-pdfview#91]
I want to use this library to show PDF file, and it worked well with the pdf file created by text. But for some PDF file created  by image that i want to display them, but i cannot.
Here are the file i used to test:
[PDF file](https://www.dropbox.com/s/ckbapzz6k2qohwh/1-1.pdf?dl=0)
And here is the result i get:
[ImageofPDF](https://www.dropbox.com/s/sypnw1787fl4ea8/A28ECB5E91C83938C6714157E53BB39792BCBF01BB380DEB20pimgpsh_fullsize_distr.jpg?dl=0)

How can i read the kind of pdf?

**Comment by PetarAnastasov** [comment]
I have the same issue. I have a pdf file that i load in pdfview. And i add an image to it on button click. After the image is added it is not shown right away but i save the file with the image on SD card. After that i wan't to open that file from the SD card using the same pdfviewer but the app crashes with "error loading page". I even tried destroying the pdfview and create a new one but still same error. I tried destroying and reopening the activity but still same error. I dont think the pdf with the image inside is corrupted because i can open that file with my phones built-in pdfviewer.

**Comment by JoanZapata** [comment]
Unfortunately this is related to the decoding library (Vudroid) and I can't do much about it. I don't think there's a workaround expect by changing the underlying library, so I'm closing this for now.
